name: Release
on: workflow_dispatch
permissions: write-all


jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspi_4_bookworm:20231109
    - name: fuse
      run: |
          sudo apt-get update
          sudo apt-get -y install libfuse2
    - name: Missing files
      run: |
        sudo apt update
        sudo apt install libc6
    - name: Download Binary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: floorp.AppImage
        path: 'dist'

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Floorp AppImage Build
        automatic_release_tag: release
        prerelease: false
        files: |
          dist/
        repo_token: ${{ secrets.GITHUB_TOKEN }}

